mutation insertEvent(
  $eventName: String!
  $participants: [participants_insert_input!]!
) {
  insert_events_one(
    object: { name: $eventName, participants: { data: $participants } }
  ) {
    id
    name
    participants {
      id
      name
    }
  }
}

mutation createEvent($eventName: String!, $participants: [Participant!]!) {
  createEvent(input: { eventName: $eventName, participants: $participants }) {
    id
    name
    participants {
      id
      name
    }
  }
}
