query queryEventById($eventId: uuid!) {
  events(where: { id: { _eq: $eventId } }) {
    id
    name
    payments {
      id
      name
      amount
      createdAt
      whoShouldPay {
        participant {
          id
          name
        }
      }
      whoPaid {
        id
        name
      }
    }
    payments_aggregate {
      aggregate {
        sum {
          amount
        }
      }
    }
  }
}
# 4d13f0e5-a25a-4537-9590-b6ec98cfc4ac
query getEvent($eventId: String!) {
  event(eventId: $eventId) {
    name
    payments {
      id
      name
      whoShouldPay {
        id
        name
      }
    }
  }
}
