mutation createEvent(
  $eventName: String!
  $participants: [ParticipantForEventInput!]!
) {
  createEvent(input: { eventName: $eventName, participants: $participants }) {
    id
    name
    participants {
      id
      name
    }
  }
}
