mutation createPayment(
  $amount: Int!
  $eventId: String!
  $name: String!
  $whoPaidId: Int!
  $whoShouldPay: [WhoShouldPayInput!]!
) {
  addPayment(
    input: {
      amount: $amount
      eventId: $eventId
      name: $name
      whoPaidId: $whoPaidId
      whoShouldPay: $whoShouldPay
    }
  ) {
    id
  }
}
