query getPayments($eventId: String!) {
  payments(eventId: $eventId) {
    id
    name
    amount
    createdAt
    whoShouldPay {
      id
      name
      ratio
    }
    whoPaid {
      id
      name
    }
  }
}
