query getResult($eventId: String!) {
  getResult(eventId: $eventId) {
    id
    name
    sumPrice
    transactions {
      from {
        id
        name
        shouldHavePaid
      }
      to {
        amount
        name
        participantId: id #field名はidだとキャッシュが走り、resultがおかしくなるためエイリアスを使う
      }
    }
  }
}
