query queryEventForAdd($eventId: uuid!) {
  events(where: { id: { _eq: $eventId } }) {
    id
    name
    participants {
      id
      name
    }
  }
}

query getEventForAdd($eventId: String!) {
  event(eventId: $eventId) {
    id
    name
    participants {
      id
      name
    }
  }
}
