query querySumPrice($eventId: uuid!) {
  events(where: { id: { _eq: $eventId } }) {
    id
    payments_aggregate {
      aggregate {
        sum {
          amount
        }
      }
    }
  }
}

query getSumPrice($eventId: String!) {
  event(eventId: $eventId) {
    id
    sumPrice
  }
}
