name: CI

on:
  pull_request:
    branches: [main]

env:
  NEXT_PUBLIC_GRAPHQL_ENDPOINT: ${{secrets.NEXT_PUBLIC_GRAPHQL_ENDPOINT}}
  NEXT_PUBLIC_LIFF_ID: ${{secrets.NEXT_PUBLIC_LIFF_ID}}
  NODE_ENV: preview
jobs:
  lint-and-test:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - uses: actions/checkout@v1
      - name: pnpm install
        run: pnpm install
      - name: pnpm generate
        run: pnpm generate
      - name: Run eslint
        run: pnpm lint
      - name: Run Jest
        run: pnpm test
