name: CI

on:
  pull_request:
    branches: [main]

env:
  NEXT_PUBLIC_X_HASURA_ADMIN_SECRET: ${{secrets.NEXT_PUBLIC_X_HASURA_ADMIN_SECRET}}
  NEXT_PUBLIC_GRAPHQL_ENDPOINT: ${{secrets.NEXT_PUBLIC_GRAPHQL_ENDPOINT}}
  NEXT_PUBLIC_GRAPHQL_REST_ENDPOINT: ${{secrets.NEXT_PUBLIC_GRAPHQL_REST_ENDPOINT}}
  NEXT_PUBLIC_LIFF_ID: ${{secrets.NEXT_PUBLIC_LIFF_ID}}
  X_HASURA_ADMIN_SECRET_FOR_CODEGEN: ${{secrets.X_HASURA_ADMIN_SECRET_FOR_CODEGEN}}
jobs:
  lint-and-test:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install
      - name: yarn generate
        run: yarn generate
      - name: Run eslint
        run: yarn lint
      - name: Run Jest
        run: yarn test
